language: node_js
node_js:
  - '16' # 指定Node.js的版本为16

# 启用corepack以使用pnpm
before_install:
  - corepack enable
  - corepack prepare pnpm@latest --activate

# 安装项目依赖
install:
  - pnpm install

# 构建项目
script:
  - pnpm run build